# This workflow runs build and unit test on push

name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Gradle
      run: gradle build -x test
    
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Run unit tests
      run: gradle build test
      
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: Test Report - ${{ github.sha }}
        path: build/reports/tests/test/